spring:
  cloud:
    stream:
      function:
        definition: crashDetectionProcessor
      bindings:
        crashDetectionProcessor-in-0:
          destination: ${INPUT_QUEUE:telematics_stream}
          # No consumer group - read directly from queue
        crashDetectionProcessor-out-0:
          destination: ${OUTPUT_QUEUE:crash_reports}
      rabbit:
        bindings:
          crashDetectionProcessor-in-0:
            consumer:
              acknowledge-mode: auto
              retry-max-attempts: ${RETRY_MAX_ATTEMPTS:3}
              retry-initial-interval: ${RETRY_INTERVAL:1000}
  
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
    connection-timeout: ${RABBITMQ_CONNECTION_TIMEOUT:60000}
    requested-heartbeat: ${RABBITMQ_HEARTBEAT:60}
    connection-recovery-interval: ${RABBITMQ_RECOVERY_INTERVAL:5000}
    publisher-confirms: ${RABBITMQ_PUBLISHER_CONFIRMS:true}
    publisher-returns: ${RABBITMQ_PUBLISHER_RETURNS:true}
    cache:
      channel:
        size: ${RABBITMQ_CHANNEL_CACHE_SIZE:25}
      connection:
        mode: ${RABBITMQ_CONNECTION_MODE:channel}
    listener:
      simple:
        retry:
          enabled: ${RABBITMQ_RETRY_ENABLED:true}
          initial-interval: ${RABBITMQ_RETRY_INITIAL:2000}
          max-attempts: ${RABBITMQ_RETRY_MAX_ATTEMPTS:10}
          max-interval: ${RABBITMQ_RETRY_MAX_INTERVAL:30000}
          multiplier: ${RABBITMQ_RETRY_MULTIPLIER:2.0}
        acknowledge-mode: auto
        prefetch: ${RABBITMQ_PREFETCH:1}
    startup:
      max-wait-time: ${RABBITMQ_STARTUP_MAX_WAIT:300}
      check-interval: ${RABBITMQ_STARTUP_CHECK_INTERVAL:5}

crash-detection:
  g-force-threshold: ${G_FORCE_THRESHOLD:4.0}
  speed-threshold: ${SPEED_THRESHOLD:5.0}

spark:
  app:
    name: ${SPARK_APP_NAME:CrashDetectionProcessor}
  master: ${SPARK_MASTER:local[*]}
  sql:
    adaptive:
      enabled: ${SPARK_ADAPTIVE_ENABLED:true}
      coalescePartitions:
        enabled: ${SPARK_COALESCE_ENABLED:true}
  streaming:
    trigger:
      interval: ${SPARK_TRIGGER_INTERVAL:2 seconds}
  processing:
    window:
      duration: ${SPARK_WINDOW_DURATION:30 seconds}
  storage:
    enabled: ${SPARK_STORAGE_ENABLED:true}
    path: ${SPARK_STORAGE_PATH:hdfs://namenode:9000/telemetry-data}
    format: ${SPARK_STORAGE_FORMAT:parquet}
    partitioning:
      enabled: ${SPARK_PARTITIONING_ENABLED:true}
      columns: ${SPARK_PARTITION_COLUMNS:["policy_id", "date"]}
    compression: ${SPARK_COMPRESSION:snappy}
    write-mode: ${SPARK_WRITE_MODE:append}

logging:
  level:
    com.insurancemegacorp.crashdetection: ${LOG_LEVEL:INFO}
    org.springframework.amqp: WARN